# Habit Tracker API

@baseURL = http://localhost:8000/api/v1/habits

@compURL = http://localhost:8000/api/v1/completions


### POST REQUEST
POST {{baseURL}}
Content-Type: application/json

{
  "name": "WALK",
  "color": "#ffff",
  "isArchived": false
}


### GET Request
GET {{baseURL}}


### PATCH REQUEST
PATCH {{baseURL}}
Content-Type: application/json

{
  "_id":"6a8e5f1ec95faa9b50133e11",
  "isArchived": true
}


### DELETE REQUEST
DELETE {{baseURL}}
Content-Type: application/json

{
  "_id": "6a8d3a6322c6c8ccc9c57650"
}


### POST COMPLETION REQUEST
POST {{compURL}}
Content-Type: application/json

{
  "habitId": "6a8e5f1ec95faa9b50133e11",
  "completedOn": "2026-08-05T03:35:58.516Z"
}

###Get Completion Request
GET {{compURL}}


###Delete Completion Request
DELETE {{compURL}}
Content-Type: application/json

{
  "_id": "6a9660072c188c2a0f59df7e"
}


