#Habit Tracker API

@baseURL = http://localhost:8000/api/v1/habits

##POST REQUEST

POST {{baseURL}}
Content-Type: application/json


{
    "name": "Drink Water",
    "color": "#ffff",
    "isArchived": false
}


##GET REQUEST

##PATCH REQUEST

##DELETE REQUEST