# Habit Tracker API

@baseURL = http://localhost:8000/api/v1/habits


### POST REQUEST
POST {{baseURL}}
Content-Type: application/json

{
  "name": "DRINK MILK",
  "color": "#ffff",
  "isArchived": false
}


### GET Request
GET {{baseURL}}


### PATCH REQUEST
PATCH {{baseURL}}
Content-Type: application/json

{
  "_id":"6a8d29386743a818f6572c8a",
  "isArchived": true
}


### DELETE REQUEST
DELETE {{baseURL}}/ID_HERE
